name: nche
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  otp_text_field: ^1.1.3
  intl_phone_field: ^3.1.0
  persistent_bottom_nav_bar: ^4.0.2
  video_player: ^2.4.5
  flutter_speed_dial: ^6.0.0
  flutter_sound: ^9.2.13
  permission_handler: ^10.0.0
  audioplayers: ^1.0.1
  file_picker: ^4.6.1
  image_picker: ^0.8.5+3

  provider: ^6.0.3

  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.9
  location: ^4.4.0
  flutter_svg: ^1.1.1+1
  flutter_native_splash: ^2.2.7

  #firebase Database
  cloud_firestore: ^3.4.3
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  google_sign_in: ^5.4.0
  firebase_storage: ^10.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_native_splash:
  #flutter pub run flutter_native_splash:create
  #color: "#283547"
  #image: assets/logos.png
  background_image: assets/splash.png
  android: true
  ios: true

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
