// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBntv7CgyXcv1kzLhKwUyMI-ERKCkDSQU',
    appId: '1:447256031033:web:8a9bc914d206660cac42e8',
    messagingSenderId: '447256031033',
    projectId: 'nche-application',
    authDomain: 'nche-application.firebaseapp.com',
    storageBucket: 'nche-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQbe2voRGGC1o7dVNVnRWfura5fj50DGE',
    appId: '1:447256031033:android:c8f339414dd77f33ac42e8',
    messagingSenderId: '447256031033',
    projectId: 'nche-application',
    storageBucket: 'nche-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjCxur1uzHyVaFab_y4EGq1KgNXWZFgB0',
    appId: '1:447256031033:ios:cdbea004adbeaaadac42e8',
    messagingSenderId: '447256031033',
    projectId: 'nche-application',
    storageBucket: 'nche-application.appspot.com',
    androidClientId: '447256031033-u494quetoana690098dqaoal18bk4jsv.apps.googleusercontent.com',
    iosClientId: '447256031033-j10dc2f0dt86upk14imob3v2hqqio41n.apps.googleusercontent.com',
    iosBundleId: 'com.example.nche',
  );
}
